### DISCUSSION TITLE
How to add a dark mode switch to my blog?

### DISCUSSION THREAD

**Discussion by ghost** [datenstrom/community#1030] [Ask a question] [answered]
(This is not a question, so, the moderators can delete this post if they wish).

I added **dark mode switch** to my Datenstrom Yellow Blog using this tool:

[https://coliff.github.io/dark-mode-switch/index.html](https://coliff.github.io/dark-mode-switch/index.html)

[https://github.com/coliff/dark-mode-switch](https://github.com/coliff/dark-mode-switch)

I chose to paste following code into the header file (after "body") in system/layouts/header.html :

```
<div align="center" class="custom-control custom-switch">
<input type="checkbox" class="custom-control-input" id="darkSwitch">
<label class="custom-control-label" for="darkSwitch">Dark Mode</label>
</div>
```

Inside "head", I pasted this code:

```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="http://www.yourdomain.com/dark-mode.css">
```

Inside the new "dark-mode.css", you will invert the colors of your theme. Well, my theme is the "Stockholm", and bellow is an example:

```
[data-theme="dark"] {
    background-color: #000000;
    color: #aeaeae;
}

[data-theme="dark"] a {
    color: #bc7c00;
}

[data-theme="dark"] a:hover {
    color: #bc7c00;
}

[data-theme="dark"] h1 {
    color: #efefef;
}

[data-theme="dark"] h2 {
    color: #efefef;
}

[data-theme="dark"] h3 {
    color: #efefef;
}

[data-theme="dark"] h4 {
    color: #efefef;
}

[data-theme="dark"] h5 {
    color: #efefef;
}

[data-theme="dark"] h6 {
    color: #efefef;
}
```

A peaceful week for everybody.

**Comment by xrat** [comment]
I've implemented a dark mode switch based on Coliff's approach, too, in 1 project that uses the [Wittstock theme](https://github.com/schulle4u/yellow-wittstock).

In `layouts/wittstock-header.html` I added to `<head>`:

``` html
<?php
$assetLocation = $this->yellow->system->get("coreServerBase").$this->yellow->system->get("coreAssetLocation");
echo "<script type=\"text/javascript\" defer=\"defer\" src=\"{$assetLocation}dark-mode-switch.js\"></script>\n";
?>
```

and to `<header>`:

``` html
<div id="darkSwitch">🌓</div>
```

My `dark-mode-switch.js` is based on Coliff's:

``` javascript
// loosely based on https://github.com/coliff/dark-mode-switch

var darkSwitch = document.getElementById("darkSwitch");
window.addEventListener("load", function () {
  if (darkSwitch) {
    initTheme();
    darkSwitch.addEventListener("click", function () {
      toggleDark();
    });
    darkSwitch.addEventListener("dblclick", function () {
      localStorage.removeItem("darkSwitch");
    });
  }
});

function initTheme() {
  if (localStorage.getItem("darkSwitch") !== null) {
    if (localStorage.getItem("darkSwitch") === "dark") {
      document.body.setAttribute("data-theme", "dark")
    }
    if (localStorage.getItem("darkSwitch") === "light") {
      document.body.setAttribute("data-theme", "light")
    }
  }
}

function toggleDark() {
  if (document.body.getAttribute("data-theme") === null
    || document.body.getAttribute("data-theme") ==="dark") {
    document.body.setAttribute("data-theme", "light");
    localStorage.setItem("darkSwitch", "light");
  } else {
    if (document.body.getAttribute("data-theme") ==="light") {
      document.body.setAttribute("data-theme", "dark");
      localStorage.setItem("darkSwitch", "dark");
    }
  }
}
```

Finally, for the CSS in Wittstock fortunately one only needs to change a bunch of variables:

``` css
[data-theme="dark"] {
  color-scheme: dark;
  --accent: #ac7900;
  --accent-bg: #2b2b2b;
  --accent-hover: #ffe099;
  --accent-text: #111;
  --bg: #111;
  --border: #898EA4;
  --code: #eb8b8b;
  --disabled: #111;
  --hljsnumber: #a1a1ff;
  --marked: #ffdd33;
  --notice1-bg: #7f5f00;
  --notice2-bg: #600000;
  --notice3-bg: #2b2b2b;
  --preformatted: #ccc;
  --text: #dcdcdc;
  --text-light: #ababab;
  --th-bg: #222;
}
[data-theme="light"] {
  --accent: #0d47a1;
  --accent-bg: #f5f7ff;
  --accent-hover: #1266e2;
  --accent-text: #fff;
  --bg: #fff;
  --border: #898EA4;
  --code: #d81b60;
  --disabled: #efefef;
  --hljsnumber: #00c;
  --marked: #ffdd33;
  --notice1-bg: #ffebb3;
  --notice2-bg: #ffc9c9;
  --notice3-bg: #cce9ff;
  --preformatted: #444;
  --text: #212121;
  --text-light: #585858;
  --th-bg: #ddd;
}
```

Plus some CSS for the toggle switch:

``` css
#darkSwitch {
  cursor: pointer;
  float: right;
  margin: .5rem .2rem;
  opacity: 70%;
}
#darkSwitch:hover {
  opacity: 95%;
}
```
